In [1]:
import numpy as np
import random
import matplotlib.pyplot as plt
import tsp_traditional as tsp

In [2]:
visu_city = 0
show_stat = 1
gen = 500
pop_size = 30
cross_rate = 0.8
muta_rate = 0.8

In [3]:
x, y, n = tsp.load_data('test.txt', visu_city)
pop = tsp.init_pop(pop_size, n)

In [4]:
fit, _ = tsp.fitness(pop, x, y)

In [5]:
off = tsp.reprod(pop, fit, cross_rate, muta_rate)

In [6]:
new = tsp.nchoose_pop(pop, off, x, y)

In [7]:
print (new)

[[ 4  5  7  3  9  8 10  1  2  6]
 [ 4  5  7  3  9  8 10  1  2  6]
 [ 8  5  3  7  9  4 10  1  2  6]
 [ 8  5  3  7  9  4 10  1  2  6]
 [ 7  4  3  9  5 10  1  2  6  8]
 [ 8  5  7  3  9  4 10  1  2  6]
 [ 8  5  7  3  9  4 10  1  2  6]
 [ 8  5  7  3  9  4 10  1  2  6]
 [ 4  5  3  9 10  2  6  1  8  7]
 [ 4  3  9  2  1  6  8  7 10  5]
 [ 8  5  3  9 10  2  6  1  4  7]
 [10  5  1  6  2  9  8  7  3  4]
 [10  5  7  3  4  1  6  2  9  8]
 [10  2  1  4  9  5  6  7  3  8]
 [10  2  1  4  8  9  7  6  5  3]
 [10  2  1  8  9  5  6  7  3  4]
 [ 6  9  5  1  2 10  4  3  7  8]
 [ 5  7  3  9 10  2  6  8  4  1]
 [ 3  5  8  6  4  9 10  2  1  7]
 [10  8  6  7  2  1  5  9  3  4]
 [ 7  8 10  6  5  1  9  4  3  2]
 [ 4  9  2  6 10  5  3  1  7  8]
 [ 3  4  2  6  7  1  9 10  5  8]
 [10  7  2  4  1  9  5  8  3  6]
 [ 1  9  5  4  3  6  8  2  7 10]
 [10  8  6  7  2  1  5  9  3  4]
 [ 2  5  7  3  8 10  1  4  9  6]
 [ 2  1  4  8  6  7  5  9  3 10]
 [ 3  4  2  6  7  1  9 10  5  8]
 [ 4  9  2  6 10  5  3  1  7  8]]
